[package]
name = "dtekv_emulator"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
dtekv_emulator = { git = "https://github.com/PumpedSardines/dtekv-emulator-core", rev="a3bd981223f97ae113c7a61640fb8620c9e0c5cd" }
wasm-bindgen = "0.2.84"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
